apiVersion: v1
kind: Service
metadata:
        name: ftps-service
        labels:
                app: ftps
spec:
        selector:
                app: ftps
        type: LoadBalancer
        ports:
                - port: 20
                  name: ftps-cmd
                  targetPort: 20
                  # nodePort: 20
                - port: 21
                  name: ftps-data
                  targetPort: 21
                  # nodePort: 21
                - port: 30020
                  name: ftps-pasv-cmd
                  targetPort: 30020
                  nodePort: 30020
                - port: 30021
                  name: ftps-pasv-data
                  targetPort: 30021
                  nodePort: 30021

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: ftps-deployment
        labels:
                app: ftps
spec:
        selector:
                matchLabels:
                        app: ftps
        replicas: 1
        template:
                metadata:
                        name: ftps-pod
                        labels:
                                app: ftps
                spec:
                        containers:
                                - name: ftps-container
                                  image: ft_ftps
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 20
                                            name: ftps-cmd
                                          - containerPort: 21
                                            name: ftps-data
                                          - containerPort: 30020
                                            name: ftps-pasv-cmd
                                          - containerPort: 30021
                                            name: ftps-psv-data