apiVersion: v1
kind: Service
metadata:
        name: nginx-service
        labels:
                app: nginx
spec:
        selector:
                app: nginx
        type: LoadBalancer
        ports:
                - port: 80
                  name: nginx-http
                  targetPort: 80
                  # nodePort: 80
                - port: 443
                  name: nginx-https
                  targetPort: 443
                  # nodePort: 443
                # - port: 30022
                #   name: nginx-ssh
                #   targetPort: 30022
                #   # nodePort: 30022

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deployment
        labels:
                app: nginx
spec:
        selector:
                matchLabels:
                        app: nginx
        replicas: 1
        template:
                metadata:
                        name: nginx-pod
                        labels:
                                app: nginx
                spec:
                        containers:
                                - name: nginx-container
                                  image: ft_nginx
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 80
                                            name: nginx-http
                                          - containerPort: 443
                                            name: nginx-https
                                #           - containerPort: 30022
                                #             name: nginx-ssh
                                #   livenessProbe:
                                #         tcpSocket:
                                #                   port: 30022
                                #         initialDelaySeconds: 15
                                #         periodSeconds: 10